### PR TITLE
feat(l0): add in styles for l0 header

### PR DESCRIPTION
**Pull request by tw15egan**
## Updates to L0 Header

screen shot 2017-12-04 at 12 04 29 pm

- Added in 4 variables for theming purposes

```scss
$cloud-header-link-color: $inverse-01 !default;
$cloud-header-icon-color: $inverse-01 !default;
$cloud-header-menu-color: $brand-02 !default;
$cloud-header-background-color: $color__blue-90 !default;
```

To test theming, there is currently a `light` theme commented out in the `_cloud-header.scss` file. Simply uncomment these and recompile to verify theming works.

#### To Do 
- [ ] Update to `bx--` namespace

### CODE REVIEW

**Comment by joshblack** [comment]
@tw15egan this should go in the cloud add-on, right?

**Comment by tw15egan** [comment]
I can move it over there, I thought this was the latest work 😓

**Comment by tw15egan** [comment]
@joshblack SO that is the React repo. Where do you suggest the styles live?

**Comment by bsonefeld** [comment]
I also thought it would live in this repo. Doesn't this repo contain the Add-ons shown on the website?

**Comment by joshblack** [comment]
Pretty much everything in the bluemix add-on should be moved over to cloud, I think, just to stay consistent. Down to update either if we feel like they don't match with our expectations 😄 

@tw15egan it actually has both setup, if we need to make it styles-only we totally can though. For adding to the repo, just need to add the `_component-name.scss` file in the folder and then include it in `src/index.scss`.

**Pull request closed without merging**
